### ISSUE TITLE
Using with Create-React-App

### ISSUE THREAD

**Issue by wildtangent** [rentalutions/reactiverecord#2]
Hi 
I am trying to use your awesome looking library with a create-react-app app

However, I get the following errors when trying to build. It seems like the `/dist/index.js` is not compiled for ES5 compatibility so there are various errors thrown depending on which babel plugins you add.

I noticed that you are using ES7 features like `::` as well in your examples. It would be great if you could add something to the docs which says which plugins/presets are required, and since `create-react-app` doesn't include these by default and preset-stage-0 is deprecated in latest babel

Ideally it would work with create-react-app without ejecting. Happy to help with this if at all possible.

I'm probably just being a novice here, but hope you can help :)
 
```
Failed to compile
./node_modules/reactiverecord/dist/index.js
Module parse failed: Unexpected token (3:7)
You may need an appropriate loader to handle this file type.
| import ReactiveRecord from "./ReactiveRecord"
| export default new ReactiveRecord()
| export ReactiveRecord from "./ReactiveRecord"
| export Model from "./Model"
| export reducer from "./reducer"
This error occurred during the build time and cannot be dismissed.
```

**Comment by kyleramirez** [comment]
Hello,
You are totally correct! This does require ES7 features for use, and I apologize for this not including that as a requirement.

You'll need to include `babel-core` `babel-loader` `babel-preset-env` `babel-preset-es2015` `babel-preset-react` `babel-preset-stage-0`.

We use `babel-preset-env` to save on compiled size, but it's completely able to use only `babel-preset-es2015`.

Here is an example of a `.babelrc` file that would work:

```json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": ["> 0.4% in US"]
        },
        "include": ["transform-es2015-arrow-functions"]
      }
    ],
    "react",
    "stage-0"
  ]
}
```

Also important is to allow Webpack to load this module with `babel-loader`. Here's an example of what would work inside a Webpack config in the `module.rules` array:

```javascript
{
  test: /\.js$/,
  include: [
    path.join(__dirname),
    path.join(__dirname, "../node_modules/reactiverecord")
  ],
  use: {
    loader: "babel-loader",
    options: {
      presets: [
        [
          "env",
          {
            modules: false,
            targets: {
              browsers: ["> 0.4% in US"]
            },
            include: ["transform-es2015-arrow-functions"]
          }
        ],
        "react",
        "stage-0"
      ]
    }
  }
}
```

Notice ReactiveRecord is mentioned directly in the `include`.

Please do let me know if you have any other questions. It's exciting to think of this being useful for others. Currently I know of three production applications which use this. Thanks for reaching out!

**Comment by wildtangent** [comment]
That is awesome help! Works great now!

FYI i am using `react-app-rewired` so I don't have to eject for this feature

My `config-overrides.js` looks like this

```js
const {injectBabelPlugin} = require('react-app-rewired');


module.exports = function override(config, env) {
  //do stuff with the webpack config...
  config = injectBabelPlugin('babel-plugin-transform-function-bind', config)
  config = injectBabelPlugin('babel-plugin-transform-export-extensions', config)

  let reactiverecordConfig = {
    test: /\.js$/,
    exclude: /node_modules(?!\/reactiverecord).*$/,
    use: {
      loader: "babel-loader",
      options: {
        presets: [
          [
            "env",
            {
              modules: false,
              targets: {
                browsers: ["> 0.4% in US"]
              },
              include: ["transform-es2015-arrow-functions"]
            }
          ],
          "react",
          "stage-0"
        ]
      }
    }
  };

  config.module.rules.push(reactiverecordConfig);

  return config;
}
```

**Comment by wildtangent** [comment]
For good measure I also have
```json
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": ["> 0.4% in US"]
        },
        "include": ["transform-es2015-arrow-functions"]
      }
    ],
    "react",
    "stage-0"
  ]
}
```

in my `.babelrc` not sure if that is strictly necessary or not ;)
